INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Taipei Zoo', '動物園', '1996-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Muzha', '木柵', '1996-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Wanfang Community', '萬芳社區', '1996-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Wanfang Hospital', '萬芳醫院', '1996-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Xinhai', '辛亥', '1996-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Linguang', '麟光', '1996-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Liuzhangli', '六張犁', '1996-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Technology Building', '科技大樓', '1996-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Daan', '大安', '1996-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Zhongxiao Fuxing', '忠孝復興', '1996-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Nanjing Fuxing', '南京復興', '1996-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Zhongshan Junior High School', '中山國中', '1996-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Zhongshan', '中山', '1997-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Shuanglian', '雙連', '1997-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Minquan West Road', '民權西路', '1997-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Yuanshan', '圓山', '1997-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Jiantan', '劍潭', '1997-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Shilin', '士林', '1997-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Zhishan', '芝山', '1997-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Mingde', '明德', '1997-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Shipai', '石牌', '1997-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Qilian', '唭哩岸', '1997-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Qiyan', '奇岩', '1997-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Beitou', '北投', '1997-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Xinbeitou', '新北投', '1997-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Fuxinggang', '復興崗', '1997-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Zhongyi', '忠義', '1997-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Guandu', '關渡', '1997-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Zhuwei', '竹圍', '1997-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Hongshulin', '紅樹林', '1997-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Tamsui', '淡水', '1997-03-28');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Taipei Main', '台北車站', '1997-12-25');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Guting', '古亭', '1998-12-24');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Chiang Kai-Shek Memorial Hall', '中正紀念堂', '1998-12-24');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Nanshijiao', '南勢角', '1998-12-24');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Jingan', '景安', '1998-12-24');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Yongan Market', '永安市場', '1998-12-24');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Dingxi', '頂溪', '1998-12-24');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('National Taiwan University Hospital', '台大醫院', '1998-12-24');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Xindian', '新店', '1999-11-11');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Xindian District Office', '新店區公所', '1999-11-11');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Qizhang', '七張', '1999-11-11');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Dapinglin', '大坪林', '1999-11-11');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Jingmei', '景美', '1999-11-11');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Wanlong', '萬隆', '1999-11-11');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Gongguan', '公館', '1999-11-11');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Taipower Building', '台電大樓', '1999-11-11');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Longshan Temple', '龍山寺', '1999-12-24');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Ximen', '西門', '1999-12-24');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Shandao Temple', '善導寺', '1999-12-24');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Zhongxiao Xinsheng', '忠孝新生', '1999-12-24');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Zhongxiao Dunhua', '忠孝敦化', '1999-12-24');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Sun Yat-Sen Memorial Hall', '國父紀念館', '1999-12-24');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Taipei City Hall', '市政府', '1999-12-24');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Xinpu', '新埔', '2000-08-31');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Jiangzicui', '江子翠', '2000-08-31');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Xiaonanmen', '小南門', '2000-08-31');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Yongchun', '永春', '2000-12-30');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Houshanpi', '後山埤', '2000-12-30');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Kunyang', '昆陽', '2000-12-30');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Xiaobitan', '小碧潭', '2004-09-29');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Yongning', '永寧', '2006-05-31');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Tucheng', '土城', '2006-05-31');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Haishan', '海山', '2006-05-31');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Far Eastern Hospital', '亞東醫院', '2006-05-31');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Fuzhong', '府中', '2006-05-31');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Banqiao', 'BL板橋', '2006-05-31');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Nangang', '南港', '2008-12-25');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Songshan Airport', '松山機場', '2009-07-04');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Dazhi', '大直', '2009-07-04');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Jiannan Road', '劍南路', '2009-07-04');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Xihu', '西湖', '2009-07-04');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Gangqian', '港墘', '2009-07-04');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Wende', '文德', '2009-07-04');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Neihu', '內湖', '2009-07-04');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Dahu Park', '大湖公園', '2009-07-04');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Huzhou', '葫洲', '2009-07-04');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Donghu', '東湖', '2009-07-04');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Nangang Software Park', '南港軟體園區', '2009-07-04');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Taipei Nangang Exhibition Center', '南港展覽館', '2009-07-04');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Songjiang Nanjing', '松江南京', '2010-11-03');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Xingtian Temple', '行天宮', '2010-11-03');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Zhongshan Elementary School', '中山國小', '2010-11-03');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Daqiaotou', '大橋頭站', '2010-11-03');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Sanchong Elementary School', '三重國小', '2010-11-03');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Sanhe Junior High School', '三和國中', '2010-11-03');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('St. Ignatius High School', '徐匯中學', '2010-11-03');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Sanmin Senior High School', '三民高中', '2010-11-03');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Luzhou', '蘆洲', '2010-11-03');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Taipei Bridge', '台北橋', '2012-01-05');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Cailiao', '菜寮', '2012-01-05');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Sanchong', '三重', '2012-01-05');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Xianse Temple', '先嗇宮', '2012-01-05');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Touqianzhuang', '頭前庄', '2012-01-05');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Xinzhuang', '新莊', '2012-01-05');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Fu Jen University', '輔大', '2012-01-05');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Dongmen', '東門', '2012-09-30');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Danfeng', '丹鳳', '2013-06-29');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Huilong', '迴龍', '2013-06-29');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Xiangshan', '象山', '2013-11-24');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Taipei 101 / World Trade Center', '台北101/世貿', '2013-11-24');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Xinyi Anhe', '信義安和', '2013-11-24');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Daan Park', '大安森林公園', '2013-11-24');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Beimen', '北門', '2014-11-15');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Taipei Arena', '台北小巨蛋', '2014-11-15');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Nanjing Sanmin', '南京三民', '2014-11-15');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Songshan', '松山', '2014-11-15');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Dingpu', '頂埔', '2015-07-06');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Shisizhang', '十四張', '2020-01-31');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Xiulang Bridge', '秀朗橋', '2020-01-31');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Jingping', '景平', '2020-01-31');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Zhonghe', '中和', '2020-01-31');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Qiaohe', '橋和', '2020-01-31');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Zhongyuan', '中原', '2020-01-31');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Banxin', '板新', '2020-01-31');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Banqiao', 'Y板橋', '2020-01-31');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('Xinpu Minsheng', '新埔民生', '2020-01-31');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('XIngFu', '幸福', '2020-01-31');
INSERT INTO station (stationNameEng, stationName, startDate) VALUES ('New Taipei Industrial Park', '新北產業園區', '2020-01-31');